version: "3"

services:

  adminer:
    image: adminer
    ports:
      - 8080:8080

  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306

  redis:
    image: redis
    ports:
      - 6379:6379